#!/usr/bin/env bash

case "$1" in
    build)
        ln -sf /Users/zvyagin/Projects/az/mcsdk/output/dto/mcsdk.py /Users/zvyagin/Projects/az/mcsdk/output/test/python/dto.py
        ln -sf /Users/zvyagin/Projects/az/mcsdk/output/test/mcsdk_test.py /Users/zvyagin/Projects/az/mcsdk/output/test/python
        ;;
    *)
        ./run-python $@
        ;;
esac
